cron:
  buscar:
    estudantes: 0 39 09 * * *
file:
  uploadDir: /Users/Public/uploads01
auth0:
  audience: https://strategies_backend/api
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  sql:
    init:
      mode: always
      platform: mysql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-w1gjm8bhgii82b6s.us.auth0.com/
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
